obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.11, -0.13], [-0.11, 0.13], [0.11, 0.13], [0.11, -0.13]]
inflation_radius: 0.55
transform_tolerance: 0.3


observation_sources: scan Cliff
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
Cliff:
    data_type: PointCloud2
    topic: pcl_output
    marking: true
    clearing: false
    min_obstacle_height: 0.0
    max_obstacle_height: 0.3


map_type: costmap
