global_costmap: 
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 #before: 5.0
  publish_frequency: 1.0 #before 0.5
  static_map: true
  transform_tolerance: 1
  cost_scaling_factor: 10.0
  inflation_radius: 0.01

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

