local_costmap: 
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 6 
  height: 6
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 1
  cost_scaling_factor: 5
  inflation_radius: 0.01


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

