<?xml version="1.0"?>  
<robot name="mybot" xmlns:xacro="http://ros.org/wiki/xacro">  

  <xacro:include filename="$(find fuxi_nav_fake)/urdf/mybot.gazebo.xacro" /> 
  <xacro:property name="PI" value="3.14159265"/>

   <!-- 底盘属性 -->
    <xacro:property name="base_link_length" value="0.4275" /> <!-- base_link 长 -->
    <xacro:property name="base_link_width" value="0.40" /> <!-- base_link 宽 -->
    <xacro:property name="base_link_height" value="0.148" /> <!-- base_link 高 -->
    <xacro:property name="earth_space" value="0.03" /> <!-- 离地间距 -->
    <xacro:property name="wheel_space" value="0.269" /> <!-- 轮间距 -->

    <!-- 驱动轮属性 -->
    <xacro:property name="wheel_radius" value="0.03" /><!-- 半径 -->
    <xacro:property name="wheel_length" value="0.06" /><!-- 宽度 -->
    
    <!-- 支撑轮属性 -->
    <xacro:property name="support_wheel_radius" value="0.03" /> <!-- 支撑轮半径 -->
    <xacro:property name="support_wheel_space" value="0.2" /> <!-- 支撑轮间距 -->

  <link name="world"/>

  <joint name="base_joint" type="fixed">  
    <parent link="world"/>  
    <child link="base_link"/>  
    <origin rpy="0 0 0" xyz="0 0 ${earth_space + base_link_height / 2 }"/>  
  </joint>  
  
  <link name="base_link">  
    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="20"/>
     <inertia ixx="0.5"  ixy="0"  ixz="0" iyy="0.5" iyz="0" izz="0.05" />
    </inertial>

    <visual>  
      <geometry>  
        <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>  
      </geometry>  
      <origin rpy="0 0 0" xyz="0 0 0"/>  
      <material name="blue">  	
          <color rgba="0.8 0 0.8 0.8"/>  
      </material>  
    </visual>  

   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="${base_link_length} ${wheel_space - wheel_length} ${base_link_height}"/>
     </geometry>
   </collision>

  </link>  
 
  <link name="right_wheel_link">  
    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="1.5"/>
     <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>

    <visual>  
      <geometry>  
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>  
      </geometry>  
      <material name="black">  
        <color rgba="0 0 0 1"/>  
      </material>  
    </visual>  

    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <cylinder length="${wheel_length}" radius="${wheel_radius}"/>  
     </geometry>
    </collision> 
  </link>  
 
  <joint name="right_wheel_joint" type="continuous">  
    <axis xyz="0 0 -1"/>  
    <parent link="base_link"/>  
    <child link="right_wheel_link"/>  
    <origin rpy="${PI/2} 0 0" xyz=" 0.12 ${-wheel_space/2} ${-(earth_space + base_link_height / 2 - wheel_radius) }"/>  
    <dynamics damping="0.8"/>
  </joint> 
 
  <link name="left_wheel_link">  
    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="1.5"/>
     <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>

    <visual>  
      <geometry>  
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>  
      </geometry>  
      <material name="black">  
        <color rgba="0 0 0 1"/>  
      </material>  
    </visual>  

    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
     </geometry>
    </collision>   
  </link>  
 
  <joint name="left_wheel_joint" type="continuous">  
    <axis xyz="0 0 -1"/>  
    <parent link="base_link"/>  
    <child link="left_wheel_link"/>  
    <origin rpy="${PI/2} 0 0" xyz=" 0.12 ${wheel_space/2} ${-(earth_space + base_link_height / 2 - wheel_radius) }"/> 
    <dynamics damping="0.8"/>  
  </joint>  
 
  <link name="ball_wheel_link_right">  
    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0.5"/>
     <inertia ixx="0"  ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>

    <visual>  
      <geometry>  
        <sphere radius="${support_wheel_radius}"/>  
      </geometry>  
      <material name="black">  
        <color rgba="0 0 0 1"/>  
      </material>  
    </visual>  

    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${support_wheel_radius}"/> 
     </geometry>
    </collision>   
  </link>  

  <joint name="ball_wheel_joint_right" type="fixed">  
    <axis xyz="0 0 0"/>  
    <parent link="base_link"/>  
    <child link="ball_wheel_link_right"/>  
    <origin rpy="0 0 0" xyz="-0.12 ${-support_wheel_space / 2} ${-(earth_space + base_link_height / 2 - support_wheel_radius) }"/>  
  </joint>  
  
  <link name="ball_wheel_link_left">  
    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0.5"/>
     <inertia ixx="0"  ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>

    <visual>  
      <geometry>  
        <sphere radius="${support_wheel_radius}"/>  
      </geometry>  
      <material name="black">  
        <color rgba="0 0 0 1"/>  
      </material>  
    </visual>  

    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${support_wheel_radius}"/> 
     </geometry>
    </collision>   
  </link>  

  <joint name="ball_wheel_joint_left" type="fixed">  
    <axis xyz=" 0 0 0"/>  
    <parent link="base_link"/>  
    <child link="ball_wheel_link_left"/>  
    <origin rpy="0 0 0" xyz="-0.12 ${support_wheel_space / 2} ${-(earth_space + base_link_height / 2 - support_wheel_radius) }"/>  
  </joint>  
  
  <!-- imu sensor -->
  <link name="imu">  
    <visual>  
      <geometry>  
        <box size="0.01 0.01 0.01"/>  
      </geometry>  
      <material name="white">  
          <color rgba="1 1 1 1"/>  
      </material>  
    </visual>  
  </link>  

  <joint name="imu_joint" type="fixed">  
    <parent link="base_link"/>  
    <child link="imu"/>  
    <origin xyz="0.0 0 ${base_link_height / 2}"/>  
  </joint> 

  <!-- camera -->
  <link name="base_camera_link">  
    <visual>  
      <geometry>  
        <box size="0.04 0.04 0.02"/>  
      </geometry>  
      <material name="white">  
          <color rgba="1 1 1 1"/>  
      </material>  
    </visual>  
  </link>  

  <joint name="camera_joint" type="fixed">  
    <parent link="base_link"/>  
    <child link="base_camera_link"/>  
    <origin xyz="0.205 0 ${base_link_height / 2}"/>  
  </joint> 
  
  <!-- laser lidar -->
  <link name="base_laser_link">  
    <visual>  
      <geometry>  
        <cylinder length="0.06" radius="0.04"/>   
      </geometry>  
      <material name="white">  
          <color rgba="1 1 1 1"/>  
      </material>  
    </visual>  
  </link>  
  
  <joint name="laser_joint" type="fixed">  
    <parent link="base_link"/>  
    <child link="base_laser_link"/>  
    <origin xyz="0 0.0 ${base_link_height / 2 + 0.03}"/>  
  </joint> 

</robot>

