global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 2.00
   publish_frequency: 2.0

   track_unknown_space: true

   static_map: true
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 1.0
   inflation_radius: 10.5
   cost_scaling_factor: 2
   map_type: costmap

   obstacle_layer: 
      observation_sources: scan 
      enable: true
      footprint_clearing_enabled: true

      scan: {
            data_type: LaserScan, 
            expected_update_rate: 0.4,
            observation_persistence: 0.0,
            marking: true, 
            clearing: true,
            topic: scan
      }

   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}


