local_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 4.0
   height: 4.0
   resolution: 0.05
   transform_tolerance: 1.0
   inflation_radius: 1.5
   cost_scaling_factor: 2.0

   obstacle_layer: 
      observation_sources: scan 
      enable: true
      footprint_clearing_enabled: true

      scan: {
            data_type: LaserScan, 
            expected_update_rate: 0.4,
            observation_persistence: 0.0,
            marking: true, 
            clearing: true,
            topic: scan
      }

   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
